# Generated by Django 3.2.12 on 2023-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeepNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=False, max_length=255)),
                ('notes', models.CharField(default=False, max_length=255)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
